# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.1.dev21+gb7a5f93.d20240117'
__version_tuple__ = version_tuple = (0, 1, 1, 'dev21', 'gb7a5f93.d20240117')
