# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.1.dev18+ga7b2df6.d20240116'
__version_tuple__ = version_tuple = (0, 1, 1, 'dev18', 'ga7b2df6.d20240116')
